// Prospect Profile — Timeline events for Andréas BODIN

const TIMELINE = [
  { id: 't1', type: 'whatsapp', dir: 'sent',
    when: 'il y a 2j · 26 avril, 14h32', author: 'Sebastian Bodin',
    title: 'Message WhatsApp envoyé',
    body: "Bonjour Andréas, je vous envoie comme convenu la proposition commerciale détaillée. Disponible cette semaine pour en discuter ?" },
  { id: 't2', type: 'whatsapp', dir: 'received',
    when: 'il y a 2j · 26 avril, 16h12', author: 'Andréas BODIN',
    title: 'Réponse WhatsApp reçue',
    body: "Merci Sebastian, je regarde ça avec l'équipe et reviens vers vous d'ici jeudi." },
  { id: 't3', type: 'pipeline',
    when: 'il y a 3j · 25 avril, 10h08', author: 'Sebastian Bodin',
    title: 'Statut pipeline modifié',
    body: 'Qualifié → Proposition' },
  { id: 't4', type: 'workflow',
    when: 'il y a 4j · 24 avril, 09h00', author: 'Système',
    title: 'Étape de parcours déclenchée',
    body: "Parcours Classique · Étape 4/5 — Envoi proposition WhatsApp" },
  { id: 't5', type: 'rdv',
    when: 'il y a 5j · 23 avril, 11h00', author: 'Sebastian Bodin',
    title: 'RDV réalisé · Démo plateforme',
    body: '30 min · Visioconférence Google Meet · Compte-rendu disponible dans le calendrier' },
  { id: 't6', type: 'linkedin', dir: 'received',
    when: 'il y a 8j · 20 avril, 18h44', author: 'Andréas BODIN',
    title: 'Réponse LinkedIn reçue',
    body: "Avec plaisir, je vous propose mardi prochain à 11h." },
  { id: 't7', type: 'linkedin', dir: 'sent',
    when: 'il y a 9j · 19 avril, 09h12', author: 'Sebastian Bodin',
    title: 'Message LinkedIn envoyé',
    body: "Bonjour Andréas, je dirige le développement Andoxa pour les structures comme IÉSEG CONSEIL. Auriez-vous 20 min cette semaine ?" },
  { id: 't8', type: 'workflow',
    when: 'il y a 11j · 17 avril, 09h00', author: 'Système',
    title: 'Inscription au parcours',
    body: 'Parcours Classique · démarrage automatique' },
  { id: 't9', type: 'note',
    when: 'il y a 11j · 17 avril, 08h45', author: 'Sebastian Bodin',
    title: 'Note ajoutée',
    body: "Profil très qualifié — IÉSEG CONSEIL gère 80+ Junior-Entreprises. Approche personnalisée recommandée." },
  { id: 't10', type: 'enrich',
    when: 'il y a 12j · 16 avril, 15h22', author: 'Sebastian Bodin',
    title: 'Profil enrichi',
    body: 'Source : LinkedIn · Email professionnel · Numéro WhatsApp' },
  { id: 't11', type: 'origin',
    when: 'il y a 16j · 12 avril, 14h32', author: 'Sebastian Bodin',
    title: 'Importé depuis LinkedIn',
    body: "Via l'extension Chrome Andoxa",
    list: 'Prospection IÉSEG Conseil Avril',
    enrich: 'Profil enrichi automatiquement (poste, entreprise, localisation)' },
];

const TIMELINE_TYPES = {
  linkedin: { color: '#0a66c2', tint: '#e8f1fa', label: 'LinkedIn', icon: 'in' },
  whatsapp: { color: '#16a34a', tint: '#e8f6ec', label: 'WhatsApp', icon: 'W' },
  pipeline: { color: '#f59e0b', tint: '#fffbeb', label: 'Pipeline', icon: '↗' },
  workflow: { color: '#8b5cf6', tint: '#f5f3ff', label: 'Workflow', icon: '▶' },
  rdv:      { color: '#0ea5e9', tint: '#e0f2fe', label: 'RDV',      icon: '📅' },
  note:     { color: '#64748b', tint: '#f1f5f9', label: 'Note',     icon: '✎' },
  enrich:   { color: '#0052D9', tint: '#e8f0fd', label: 'Enrich.',  icon: '✦' },
  origin:   { color: '#0052D9', tint: '#e8f0fd', label: 'Origine',  icon: 'in' },
};

Object.assign(window, { TIMELINE, TIMELINE_TYPES });
